# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85713596f913cefa550ccfbadfce62c8cef9c30ca0af8cd5f8960c5426ad2be81fa8a8e3034445c424f08be738f08a2ac9c4292d6e1f60c005ce48e1e52bee96
  aws_secret_key: oaiushdfoahfweew
  
test:
  secret_key_base: c89ae07f1812d99199ddf606ea8b51d13664d0f53754825ed829a178f33fd18dcfc1ff19afd2f556eec5bc487e52a907d5be102e3a0e1a162177a651859b0686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
